### ISSUE TITLE
tidevice ps raise FileExistsError

### ISSUE THREAD

**Issue by youngfreeFJS** [alibaba/tidevice#359]
```
➜  ~ tidevice ps
[I 231113 15:16:13 _device:615] ProductVersion: 16.3.1
Traceback (most recent call last):
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/_device.py", line 498, in start_service
    return self._unsafe_start_service(name)
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/_device.py", line 517, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/bin/tidevice", line 8, in <module>
    sys.exit(main())
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/__main__.py", line 1010, in main
    actions[args.subparser](args)
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/__main__.py", line 606, in cmd_ps
    with d.connect_instruments() as ts:
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/_device.py", line 799, in connect_instruments
    conn = self.start_service(
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/_device.py", line 500, in start_service
    self.mount_developer_image()
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/_device.py", line 661, in mount_developer_image
    developer_img_dir = self._request_developer_image_dir()
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/_device.py", line 627, in _request_developer_image_dir
    image_path = get_developer_image_path(version)
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/site-packages/tidevice/_imagemounter.py", line 132, in get_developer_image_path
    shutil.copytree(dmg_path, image_path)
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/shutil.py", line 457, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/Users/youngfreefjs/.pyenv/versions/3.10.0/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/youngfreefjs/.tidevice/device-support/16.3'
➜  ~
```

**Comment by youngfreeFJS** [comment]
unzip is an empty dir: /Users/youngfreefjs/.tidevice/device-support/16.3
After manually downloaded and unzip it, it returned to successful.
